name: Lint Pull Request Title

on:
  pull_request_target:
    types:
      - opened
      - edited

jobs:
  pull-request-lint:
    uses: necko-actions/reusable-workflows/.github/workflows/pull-request-lint.yml@v1
